### ISSUE TITLE
Travis build is failing with Conan 1.8

### ISSUE THREAD

**Issue by hanickadot** [hanickadot/compile-time-regular-expressions#15]
```
 >> Calling 'conan create'
+-----------------+----------------------------------------------------+
| Configuration   | value                                              |
|-----------------+----------------------------------------------------|
| build_modes     |                                                    |
| name            | CTRE                                               |
| profile_name    | /tmp/tmp0KQ5bzconan_package_tools_profiles/profile |
| version         | master                                             |
| user            | ctre                                               |
| channel         | testing                                            |
+-----------------+----------------------------------------------------+
Exporting package recipe
CTRE/master@ctre/testing: Repo origin deduced by 'auto': https://github.com/hanickadot/compile-time-regular-expressions.git
CTRE/master@ctre/testing: Revision deduced by 'auto': 0c7e82f1198862f9b26d5a631137cb6145a48843
Traceback (most recent call last):
  File "/usr/local/bin/run_create_in_docker", line 11, in <module>
    load_entry_point('conan-package-tools==0.19.4', 'console_scripts', 'run_create_in_docker')()
  File "/usr/local/lib/python2.7/dist-packages/cpt/run_in_docker.py", line 45, in run
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/cpt/runner.py", line 69, in run
    test_folder=self._test_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 349, in create
    self._client_cache, self._plugin_manager)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/export.py", line 59, in cmd_export
    keep_source)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/export.py", line 142, in _export_conanfile
    output, paths, conan_ref)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/export.py", line 96, in _capture_export_scm_data
    scm_data)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/export.py", line 103, in _replace_scm_data_in_conanfile
    tree = ast.parse(content)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
Traceback (most recent call last):
  File ".conan/build.py", line 24, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cpt/packager.py", line 386, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cpt/packager.py", line 486, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cpt/runner.py", line 190, in run
    raise Exception("Error building: %s" % command)
Exception: Error building: sudo -E docker run --rm -v "/home/travis/build/hanickadot/compile-time-regular-expressions:/home/conan/project" -e CONAN_GCC_VERSIONS="8" -e CONAN_DOCKER_IMAGE="lasote/conangcc8" -e CONAN_LOGIN_USERNAME="hanickadot" -e CONAN_PASSWORD="[secure]" -e CONAN_CHANNEL="testing" -e CONAN_UPLOAD="https://api.bintray.com/conan/hanickadot/ctre@True@upload_repo" -e CONAN_REFERENCE="CTRE/master@ctre/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86@@build_type=Release@@compiler=gcc@@compiler.version=8@@[options]@@@@[env]@@@@[build_requires]@@@@" -e CONAN_USERNAME="ctre" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_TEST_FOLDER=".conan/test_package" -e PIP_DISABLE_PIP_VERSION_CHECK="1"  lasote/conangcc8 /bin/sh -c " cd project &&  run_create_in_docker "
```

**Comment by hanickadot** [comment]
It's because shebang and unicode characters in conanfile (bug in Conan 1.8)
